### ISSUE TITLE
RTP not teleporting past 1,000 coordinates.

### ISSUE THREAD

**Issue by mibby** [SuperRonanCraft/BetterRTP#17]
BetterRTP v2.9.3
Paper dev 226 (Spigot 1.14.4)

@SuperRonanCraft Did something break in BetterRTP recently with how random coordinates are generated? Ever since updating from an older version to v2.9.3, players are informing me that the RTP never teleports them to coordinates beyond 1000 x/z regardless of how many times they do it. Whereas before it was working fine and completely random. 

The world is fully pre-generated.

Config
https://paste.ubuntu.com/p/rd5zFKHxnZ/

Command attached to NPC.
```
    - '[console] rtp player %player% world'
```

**Comment by SuperRonanCraft** [comment]
In recent updates. The way custom worlds are generated are different. Instead of the section "CustomWorlds" is a list of sections instead of a subsections. So just add a '-' next to your custom world names and a space. 
You can view how to setup your config on the wiki https://github.com/SuperRonanCraft/BetterRTP/wiki/Config

**Comment by mibby** [comment]
That seemed to be it, thanks!
