### ISSUE TITLE
rtp command using more ticks than it should

### ISSUE THREAD

**Issue by marvinej** [SuperRonanCraft/BetterRTP#3]
![image](https://user-images.githubusercontent.com/994680/46187856-b667f180-c2b3-11e8-966f-2dad23335f1b.png)

every time a player uses /rtp it kills the tick rate. Can you help track this down?

**Comment by SuperRonanCraft** [comment]
So I've been trying to solve this issue, I will try to find a better way to teleport players without doing too much stress on the server, I will start to take this plugin more serious because at first it was just a play around because I was a scrub on the spigot api, lets just see what I can cook up.

**Comment by At0micA55** [comment]
marvinej what is your configuration like ? 

We have found that a little bug that can be fixed by turning Use WorldBorder (on by default) to Off

**Comment by mxs42** [comment]
Do you plan to add support for Paper async chunk loading?
