### ISSUE TITLE
Teleportation animation + 

### ISSUE THREAD

**Issue by kristouffe** [SuperRonanCraft/BetterRTP#34]
**Plugin Version**:
latest

**Request**:
Hi, could you add some minecraft effects support during teleportation delays arround or on the player. You can see it in many other teleportation plugins and it makes it a bit more funny when you 're waiting for teleportation.
The animation could even last a variable time after the teleportation.

some effect ideas: Blindness, Glowing, NetherPortalTeleportation animation (guess it's confusion or nausea).

Sounds make it already fun, animations would enhance the plugin a step further.

Thank you :)

**Comment by SuperRonanCraft** [comment]
Thank you for your request, unfortunately due to the many changes in Minecraft's particle code, this support would only be on the latest versions of Minecraft. So making would be easy for one version, but I will see if I can give this over to a particle api that would be optional to handle this once I get an appropriate api to add this. For now, I will set this aside, but I would love to revisit this when I can!

**Comment by SuperRonanCraft** [comment]
Currently working on implementing this with a library, I will be posting this update very soon, just wanted to give you a heads up.
