### ISSUE TITLE
Per world cooldown

### ISSUE THREAD

**Issue by christaylor201** [SuperRonanCraft/BetterRTP#53]
**Plugin Version**:
3.0.3

**Request**:
Add per world cooldown.

**How/Why**:
Servers might have multiple worlds with specific uses, for example we have main worlds and also mining worlds which are reset each month.

I'd be nice if a different cooldown could be set for each world, e.g. higher for the main worlds and lower for the mining worlds. This would encourage players to use the mining worlds to gather resources, not the main ones.

**Additional Context**:
This is an idea from one of our players – I'd great to have such a feature, but it's not necessary, therefore I wouldn't mind if you declined this.

**Comment by SuperRonanCraft** [comment]
The way worlds are setup where they are fairly dynamic MIGHT allow for this feature without a huge cooldown recode. But this would be a fairly large change in how cooldowns are stored and controlled. I would say this might be a little far away to implement, but I will keep this in mind.
Thank you for the suggestions!

**Comment by RealBarthold** [comment]
I was a bit sad to see this wasn't included in the very customizable per-world settings. So I would just like to second this feature request! I would love to see this in a future update.

What I specifically need, is a cooldown difference between "Normal worlds" and "Nether worlds", to be able to allow players to use RTP in the Nether as well. So I was wondering: If you were to program a seperate cooldown for normal worlds and one for nether worlds - Would that still be a large change in how cooldowns are stored? Or would that be a simpler solution?

Either way, I plan to use your plugin, since it's better than all the others with the current features. I will try to find alternative ways to make seperate cooldowns for the time being.

Have a nice day!

**Comment by SuperRonanCraft** [comment]
With the new cooldowns feature being rethought, world cooldowns is around the corner ;) I will continue developing and adding this VERY soon.

**Comment by christaylor201** [comment]
I'm glad to hear this!

**Comment by ElTuna** [comment]
yeah please i also expect this feature to be added soon <3 nice plugin btw

**Comment by SuperRonanCraft** [comment]
After many months of work, this feature is finally out on the much awaited 3.4.0 update! Check it out here https://www.spigotmc.org/resources/betterrtp.36081/update?update=452508

**Comment by ElTuna** [comment]
thanks sir! :D

**Comment by christaylor201** [comment]
Thank you for your tremendous effort, I appreciate it a lot – our players will definitely enjoy this feature!
